module.exports = {
  theme: {
    screens: {},
    colors: {
      primaryDark: '#1F1D2B',
      primarySoft: '#252836',
      primaryBlueAccent: '#12CDD9',
      secondary: '#F1F5F5',
      secondaryGreen: '#22B07D',
      secondaryOrange: '#FF8700',
      secondaryRed: '#FF7256',
      textBlack: '#171725',
      textDarkGrey: '#696974',
      textGrey: '#92929D',
      textWhiteGrey: '#F1F1F5',
      textWhite: '#FFFFFF',
      textLineDark: '#EAEAEA',
      white: '#FFFFFF',
      black: '#000000',
      blueFB: '#4267B2',
    },
    fontFamily: {
      montserrat: ['Montserrat-Regular'],
      montserratMedium: ['Montserrat-Medium'],
      montserratSemiBold: ['Montserrat-SemiBold'],
      montserratBold: ['Montserrat-Bold'],
      montserratExtraBold: ['Montserrat-ExtraBold'],
      montserratLight: ['Montserrat-Light'],
      montserratExtraLight: ['Montserrat-ExtraLight'],
      montserratThin: ['Montserrat-Thin'],
    },
    extend: {},
  },
};
